name: security-action
on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.png* *.pdf* *.md* *Dockerfile *.yml'
          path: .

      - name: Publicando Artefato
        uses: actions/upload-artifact@v4
        with:
          name: pacoteVeracode
          path: veracode.zip

  veracode-sast-pipeline_scan:
    needs: package
    runs-on: ubuntu-latest
    name: veracode pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode

      - name: veracode pipeline-scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.15
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: "veracode.zip"

  veracode-sca:
    needs: package
    runs-on: ubuntu-latest
    name: veracode sca

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: run veracode sca
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.10
        with:
          github_token: ${{ secrets.GB_TOKEN }}
          path: .
          quick: false

  veracode-iac-scan:
    needs: package
    runs-on: ubuntu-latest
    name: veracode container iac secrets scanning
      
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets Scanning
        uses: veracode/container_iac_secrets_scanning@v1.0.2
        with: 
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          command: "scan" 
          type: "directory"
          format: "table"
          debug: false
          fail_build: false

  veracode-sast-sandbox-scan:
    needs: [ package, veracode-sast-pipeline_scan, veracode-sca, veracode-iac-scan ]
    name: sast sandbox scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode
          
      - name: veracode sast sandbox scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-javascript-api'
          createprofile: true
          teams: '${{ secrets.VERACODE_TEAM }}'
          filepath: 'veracode.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          createsandbox: 'true'
          sandboxname: "${{ github.ref }}"
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode-sast-policy-scan:
    needs: [ package, veracode-sast-pipeline_scan, veracode-sca, veracode-iac-scan, veracode-sast-sandbox-scan ]
    name: sast policy scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode
          
      - name: veracode sast policy scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-javascript-api'
          createprofile: true
          teams: '${{ secrets.VERACODE_TEAM }}'
          filepath: 'veracode.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 12
